# Copyright 2022 Contributors to the Veraison project.
# SPDX-License-Identifier: Apache-2.0

CFLAGS = -Wall
LDLIBS = -framework Security -framework CoreFoundation -liconv -lSystem -lresolv -lc -lm -liconv
include build.mk
